Debug.

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -29,72 +29,72 @@ jobs:
           make prepare-release version=$(grep -oP '(?<=const Version = ")[^"]+' "./pkg/version/version.go")
           git diff --exit-code
       
-  build_and_test_linux:
-    runs-on: ubuntu-latest
-    needs: checks
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: ${{ env.GO_VERSION }}
-          cache: false
-      - name: Run Tests
-        run: |
-          has_failure=false
-          orig_dir=$(pwd)
+  # build_and_test_linux:
+  #   runs-on: ubuntu-latest
+  #   needs: checks
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup Go
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         go-version: ${{ env.GO_VERSION }}
+  #         cache: false
+  #     - name: Run Tests
+  #       run: |
+  #         has_failure=false
+  #         orig_dir=$(pwd)
 
-          while read -r modfile; do
+  #         while read -r modfile; do
 
-            echo "$modfile"
-            cd $(dirname "$modfile")
-            output=$(go test -v ./...)
-            echo "$output" | grep -q "FAIL"
+  #           echo "$modfile"
+  #           cd $(dirname "$modfile")
+  #           output=$(go test -v ./...)
+  #           echo "$output" | grep -q "FAIL"
 
-            if [ $? -eq 0 ]; then
-              has_failure=true
-              echo "Exit code: $?"
-            fi
+  #           if [ $? -eq 0 ]; then
+  #             has_failure=true
+  #             echo "Exit code: $?"
+  #           fi
 
-            echo "$output"
-            cd "$orig_dir"
-          done < <(find . -name go.mod)
+  #           echo "$output"
+  #           cd "$orig_dir"
+  #         done < <(find . -name go.mod)
 
-          if [ "$has_failure" = true ]; then
-            exit 1
-          fi
+  #         if [ "$has_failure" = true ]; then
+  #           exit 1
+  #         fi
 
-  build_and_test_windows:
-    runs-on: windows-latest
-    needs: checks
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: ${{ env.GO_VERSION }}
-          cache: false
-      - name: Run Tests
-        run: |
-          $hasFailure = $false
+  # build_and_test_windows:
+  #   runs-on: windows-latest
+  #   needs: checks
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup Go
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         go-version: ${{ env.GO_VERSION }}
+  #         cache: false
+  #     - name: Run Tests
+  #       run: |
+  #         $hasFailure = $false
 
-          Get-ChildItem -Recurse -Filter 'go.mod' | ForEach-Object {
-              Push-Location $_.Directory
+  #         Get-ChildItem -Recurse -Filter 'go.mod' | ForEach-Object {
+  #             Push-Location $_.Directory
               
-              $output = go test -v ./...
-              $exitCode = $LASTEXITCODE
-              $output | ForEach-Object { if ($_ -match 'FAIL') { $_ } }
-              if ($exitCode -ne 0) {
-                  $hasFailure = $true
-              }
-              Pop-Location
-          }
+  #             $output = go test -v ./...
+  #             $exitCode = $LASTEXITCODE
+  #             $output | ForEach-Object { if ($_ -match 'FAIL') { $_ } }
+  #             if ($exitCode -ne 0) {
+  #                 $hasFailure = $true
+  #             }
+  #             Pop-Location
+  #         }
 
-          if ($hasFailure) {
-              exit 1
-          }
+  #         if ($hasFailure) {
+  #             exit 1
+  #         }
         
   build_and_test_darwin_arm64:
     # Based on https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
@@ -117,19 +117,19 @@ jobs:
           for modfile in $go_mod_files; do
 
             echo "$modfile"
-            cd $(dirname "$modfile")
-            output=$(go test -v ./...)
-            echo "$output"
-            echo "$output" | grep -q "FAIL"
+            # cd $(dirname "$modfile")
+            # output=$(go test -v ./...)
+            # echo "$output"
+            # echo "$output" | grep -q "FAIL"
 
-            if [ $? -eq 0 ]; then
-              has_failure=true
-              echo "Exit code: $?"
-            fi
+            # if [ $? -eq 0 ]; then
+            #   has_failure=true
+            #   echo "Exit code: $?"
+            # fi
 
-            echo "Has Failure: $has_failure"
+            # echo "Has Failure: $has_failure"
 
-            cd "$orig_dir"
+            # cd "$orig_dir"
           done
 
           if [ "$has_failure" = true ]; then
