Debug.

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -122,13 +122,13 @@ jobs:
 
             go test -v ./... > test_output.txt 2>&1 || true
             
-            echo $(cat test_output.txt)
+            cat test_output.txt
             
-            cat test_output.txt | (! grep -q "FAIL")
-            if [ $? -eq 0 ]; then
-              has_failure=true
-              echo "Exit code: $?"
-            fi
+            # cat test_output.txt | (! grep -q "FAIL")
+            # if [ $? -eq 0 ]; then
+            #   has_failure=true
+            #   echo "Exit code: $?"
+            # fi
 
             # echo "Has Failure: $has_failure"
 
