Unified testing of pipelines.

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -29,84 +29,79 @@ jobs:
   #         make prepare-release version=$(grep -oP '(?<=const Version = ")[^"]+' "./pkg/version/version.go")
   #         git diff --exit-code
       
-  # build_and_test_linux:
-  #   runs-on: ubuntu-latest
-  #   # needs: checks
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #     - name: Setup Go
-  #       uses: actions/setup-go@v4
-  #       with:
-  #         go-version: ${{ env.GO_VERSION }}
-  #         cache: false
-  #     - name: Run Tests
-  #       run: |
-  #         set +e
+  build_and_test_linux:
+    runs-on: ubuntu-latest
+    # needs: checks
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: ${{ env.GO_VERSION }}
+          cache: false
+      - name: Run Tests
+        run: |
+          set +e
           
-  #         has_failure=false
-  #         orig_dir=$(pwd)
+          has_failure=false
+          orig_dir=$(pwd)
 
-  #         go_mod_files=$(find . -name go.mod)
-  #         for modfile in $go_mod_files; do
-  #           cd $(dirname "$modfile")
+          go_mod_files=$(find . -name go.mod)
+          for modfile in $go_mod_files; do
+            cd $(dirname "$modfile")
 
-  #           echo "Processing tests for module $modfile"
-  #           go test -v ./... > test_output.txt 2>&1
-            
-  #           # Reporting test output.
-  #           cat test_output.txt
-            
-  #           cat test_output.txt | (grep -q "FAIL")
-  #           if [ $? -eq 0 ]; then
-  #             has_failure=true
-  #           fi
+            echo "Processing tests for module $modfile"
+            go test -v ./...
+            if [[ $? != 0 ]]; then
+              has_failure=true
+            fi           
 
-  #           cd "$orig_dir"
-  #         done
+            cd "$orig_dir"
+          done
 
-  #         if [ "$has_failure" = true ]; then
-  #           echo "Some tests failed"
-  #           exit 1
-  #         fi
+          if [ "$has_failure" = true ]; then
+            echo "Some tests failed"
+            exit 1
+          fi
 
-  #         echo "All tests passed"
-  #       shell: bash
+          echo "All tests passed"
+        shell: bash
 
-  # build_and_test_windows:
-  #   runs-on: windows-latest
-  #   # needs: checks
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #     - name: Setup Go
-  #       uses: actions/setup-go@v4
-  #       with:
-  #         go-version: ${{ env.GO_VERSION }}
-  #         cache: false
-  #     - name: Run Tests
-  #       run: |
-  #         $hasFailure = $false
+  build_and_test_windows:
+    runs-on: windows-latest
+    # needs: checks
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Setup Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: ${{ env.GO_VERSION }}
+          cache: false
+      - name: Run Tests
+        run: |
+          $hasFailure = $false
 
-  #         Get-ChildItem -Recurse -Filter 'go.mod' | ForEach-Object {
-  #             Push-Location $_.Directory
+          Get-ChildItem -Recurse -Filter 'go.mod' | ForEach-Object {
+              Push-Location $_.Directory
 
-  #             Write-Host "Processing tests for module $($_.FullName)"        
-  #             go test -v ./...
-  #             if ($LASTEXITCODE -ne 0) {
-  #               $hasFailure = $true
-  #             }
+              Write-Host "Processing tests for module $($_.FullName)"        
+              go test -v ./...
+              if ($LASTEXITCODE -ne 0) {
+                $hasFailure = $true
+              }
 
-  #             Pop-Location
-  #         }
+              Pop-Location
+          }
 
-  #         if ($hasFailure) {
-  #           Write-Host "Some tests failed"
-  #           exit 1
-  #         }
+          if ($hasFailure) {
+            Write-Host "Some tests failed"
+            exit 1
+          }
 
-  #         Write-Host "All tests passed"
-  #       shell: pwsh
+          Write-Host "All tests passed"
+        shell: pwsh
         
   build_and_test_darwin_arm64:
     # Based on https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
