Improving readibility for linux build and test.

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -42,7 +42,29 @@ jobs:
           cache: false
       - name: Run Tests
         run: |
-          find . -name go.mod -execdir go test -v ./... \; | (! grep FAIL)
+          has_failure=false
+          orig_dir=$(pwd)
+
+          find . -name go.mod | while read -r modfile; do
+            cd $(dirname "$modfile")
+
+            output=$(go test -v ./...)
+
+            echo "$output" | grep -q "FAIL"
+
+            if [ $? -eq 0 ]; then
+              has_failure=true
+              echo "Exit code: $?"
+            fi
+
+            echo "$output"
+            cd "$orig_dir"
+
+          done
+
+          if [ "$has_failure" = true ]; then
+            exit 1
+          fi
 
   build_and_test_windows:
     runs-on: windows-latest
