Start debugging Windows configuration.

diff --git a/.github/workflows/buildAndTest.yml b/.github/workflows/buildAndTest.yml
--- a/.github/workflows/buildAndTest.yml
+++ b/.github/workflows/buildAndTest.yml
@@ -29,53 +29,9 @@ jobs:
   #         make prepare-release version=$(grep -oP '(?<=const Version = ")[^"]+' "./pkg/version/version.go")
   #         git diff --exit-code
       
-  build_and_test_linux:
-    runs-on: ubuntu-latest
-    # needs: checks
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Setup Go
-        uses: actions/setup-go@v4
-        with:
-          go-version: ${{ env.GO_VERSION }}
-          cache: false
-      - name: Run Tests
-        run: |
-          set +e
-          
-          has_failure=false
-          orig_dir=$(pwd)
-
-          go_mod_files=$(find . -name go.mod)
-          for modfile in $go_mod_files; do
-            cd $(dirname "$modfile")
-
-            echo "Processing tests for module $modfile"
-            go test -v ./... > test_output.txt 2>&1
-            
-            # Reporting test output.
-            cat test_output.txt
-            
-            cat test_output.txt | (grep -q "FAIL")
-            if [ $? -eq 0 ]; then
-              has_failure=true
-            fi
-
-            cd "$orig_dir"
-          done
-
-          if [ "$has_failure" = true ]; then
-            echo "Some tests failed"
-            exit 1
-          fi
-
-          echo "All tests passed"
-        shell: bash
-
-  # build_and_test_windows:
-  #   runs-on: windows-latest
-  #   needs: checks
+  # build_and_test_linux:
+  #   runs-on: ubuntu-latest
+  #   # needs: checks
   #   steps:
   #     - name: Checkout
   #       uses: actions/checkout@v4
@@ -86,27 +42,39 @@ jobs:
   #         cache: false
   #     - name: Run Tests
   #       run: |
-  #         $hasFailure = $false
+  #         set +e
+          
+  #         has_failure=false
+  #         orig_dir=$(pwd)
 
-  #         Get-ChildItem -Recurse -Filter 'go.mod' | ForEach-Object {
-  #             Push-Location $_.Directory
-              
-  #             $output = go test -v ./...
-  #             $exitCode = $LASTEXITCODE
-  #             $output | ForEach-Object { if ($_ -match 'FAIL') { $_ } }
-  #             if ($exitCode -ne 0) {
-  #                 $hasFailure = $true
-  #             }
-  #             Pop-Location
-  #         }
+  #         go_mod_files=$(find . -name go.mod)
+  #         for modfile in $go_mod_files; do
+  #           cd $(dirname "$modfile")
 
-  #         if ($hasFailure) {
-  #             exit 1
-  #         }
-        
-  build_and_test_darwin_arm64:
-    # Based on https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
-    runs-on: macos-latest
+  #           echo "Processing tests for module $modfile"
+  #           go test -v ./... > test_output.txt 2>&1
+            
+  #           # Reporting test output.
+  #           cat test_output.txt
+            
+  #           cat test_output.txt | (grep -q "FAIL")
+  #           if [ $? -eq 0 ]; then
+  #             has_failure=true
+  #           fi
+
+  #           cd "$orig_dir"
+  #         done
+
+  #         if [ "$has_failure" = true ]; then
+  #           echo "Some tests failed"
+  #           exit 1
+  #         fi
+
+  #         echo "All tests passed"
+  #       shell: bash
+
+  build_and_test_windows:
+    runs-on: windows-latest
     # needs: checks
     steps:
       - name: Checkout
@@ -118,33 +86,70 @@ jobs:
           cache: false
       - name: Run Tests
         run: |
-          set +e
+          $hasFailure = $false
+
+          Get-ChildItem -Recurse -Filter 'go.mod' | ForEach-Object {
+              Push-Location $_.Directory
+
+              Write-Host "Processing tests for module $($_.FullName)"        
+              $output = go test -v ./...
+
+              # Reporting test output.
+              Write-Host $output
+              
+              #$exitCode = $LASTEXITCODE
+              #$output | ForEach-Object { if ($_ -match 'FAIL') { $_ } }
+              #if ($exitCode -ne 0) {
+              #    $hasFailure = $true
+              #}
+              Pop-Location
+          }
+
+          if ($hasFailure) {
+              exit 1
+          }
+        
+  # build_and_test_darwin_arm64:
+  #   # Based on https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
+  #   runs-on: macos-latest
+  #   # needs: checks
+  #   steps:
+  #     - name: Checkout
+  #       uses: actions/checkout@v4
+  #     - name: Setup Go
+  #       uses: actions/setup-go@v4
+  #       with:
+  #         go-version: ${{ env.GO_VERSION }}
+  #         cache: false
+  #     - name: Run Tests
+  #       run: |
+  #         set +e
           
-          has_failure=false
-          orig_dir=$(pwd)
+  #         has_failure=false
+  #         orig_dir=$(pwd)
 
-          go_mod_files=$(find . -name go.mod)
-          for modfile in $go_mod_files; do
-            cd $(dirname "$modfile")
+  #         go_mod_files=$(find . -name go.mod)
+  #         for modfile in $go_mod_files; do
+  #           cd $(dirname "$modfile")
 
-            echo "Processing tests for module $modfile"
-            go test -v ./... > test_output.txt 2>&1
+  #           echo "Processing tests for module $modfile"
+  #           go test -v ./... > test_output.txt 2>&1
             
-            # Reporting test output.
-            cat test_output.txt
+  #           # Reporting test output.
+  #           cat test_output.txt
             
-            cat test_output.txt | (grep -q "FAIL")
-            if [ $? -eq 0 ]; then
-              has_failure=true
-            fi
+  #           cat test_output.txt | (grep -q "FAIL")
+  #           if [ $? -eq 0 ]; then
+  #             has_failure=true
+  #           fi
 
-            cd "$orig_dir"
-          done
+  #           cd "$orig_dir"
+  #         done
 
-          if [ "$has_failure" = true ]; then
-            echo "Some tests failed"
-            exit 1
-          fi
+  #         if [ "$has_failure" = true ]; then
+  #           echo "Some tests failed"
+  #           exit 1
+  #         fi
 
-          echo "All tests passed"
-        shell: bash
+  #         echo "All tests passed"
+  #       shell: bash
